// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using taaask10.data;

#nullable disable

namespace taaask10.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260403004139_test22")]
    partial class test22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("taaask10.model.Customers", b =>
                {
                    b.Property<int>("customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerid"));

                    b.Property<string>("criditcard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("sales")
                        .HasColumnType("int");

                    b.HasKey("customerid");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("taaask10.model.Product", b =>
                {
                    b.Property<int>("product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("sales")
                        .HasColumnType("int");

                    b.HasKey("product");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("taaask10.model.Sales", b =>
                {
                    b.Property<int>("salesid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("salesid"));

                    b.Property<int>("customeri")
                        .HasColumnType("int");

                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.Property<int>("storeid")
                        .HasColumnType("int");

                    b.HasKey("salesid");

                    b.HasIndex("customeri");

                    b.HasIndex("productid");

                    b.HasIndex("storeid");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("taaask10.model.Store", b =>
                {
                    b.Property<int>("storeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("storeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("sales")
                        .HasColumnType("int");

                    b.HasKey("storeid");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("taaask10.model.Sales", b =>
                {
                    b.HasOne("taaask10.model.Customers", "Customers")
                        .WithMany()
                        .HasForeignKey("customeri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("taaask10.model.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("taaask10.model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("storeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("Store");

                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
